Repository kestra-io/kestra, pull requests merged in 2023-11, with the labels that each got.

#2302 Select character encoding for file preview
  ui/src/components/executions/FilePreview.vue
  ui/src/translations.json
  webserver/src/main/java/io/kestra/webserver/controllers/ExecutionController.java
  webserver/src/main/java/io/kestra/webserver/utils/filepreview/DefaultFileRender.java
  webserver/src/main/java/io/kestra/webserver/utils/filepreview/FileRenderBuilder.java
  webserver/src/test/java/io/kestra/webserver/controllers/ExecutionControllerTest.java
  webserver/src/test/java/io/kestra/webserver/utils/filepreview/DefaultFileRenderTest.java
  webserver/src/test/resources/data/iso88591.txt
Labels: enhancement

#1650 fix(ui): Add form for anyOf type
  core/src/main/java/io/kestra/core/docs/AbstractClassDocumentation.java
  ui/src/components/flows/tasks/Task.js
  ui/src/components/flows/tasks/TaskAnyOf.vue
  ui/src/components/flows/tasks/TaskObject.vue
  ui/src/utils/init.js
Labels: frontend

#2607 fix(core): possible NPE on execution.findChilds()
  core/src/main/java/io/kestra/core/models/executions/Execution.java
Labels: backport-needed

#2606 fix(ui): avoid admin menu blinking
  ui/src/override/components/LeftMenu.vue
Labels: backport-needed
