Repository kestra-io/kestra, pull requests merged in 2025-04, with the labels that each got.

#8215 fix(cli): fix NPE for commands not requiring plugins (#8212)
  cli/src/main/java/io/kestra/cli/AbstractApiCommand.java
  cli/src/main/java/io/kestra/cli/AbstractValidateCommand.java
  cli/src/test/java/io/kestra/cli/commands/flows/FlowExportCommandTest.java
  cli/src/test/java/io/kestra/cli/commands/flows/FlowUpdatesCommandTest.java
  cli/src/test/java/io/kestra/cli/commands/flows/TemplateValidateCommandTest.java
  cli/src/test/java/io/kestra/cli/commands/namespaces/files/NamespaceFilesUpdateCommandTest.java
  cli/src/test/java/io/kestra/cli/commands/namespaces/kv/KvUpdateCommandTest.java
Labels: kind/backport-needed

#8266 fix(ui): removed reorder button when there's only one value
  ui/src/components/flows/tasks/TaskArray.vue
Labels: area/frontend

#8312 feat(cli,core): change KESTRA_ env prefix by ENV_
  build.gradle
  cli/src/main/resources/application.yml
  core/src/main/java/io/kestra/core/runners/RunContextCache.java
  core/src/test/java/io/kestra/plugin/core/flow/VariablesTest.java
Labels: kind/breaking-change

#8336 chore(system): don't emit two time a workertaskresult for RUNNING
  core/src/main/java/io/kestra/core/runners/Worker.java
Labels: kind/performance

#8246 Fixed restart trigger position for backfill column
  ui/src/components/admin/Triggers.vue
  ui/src/components/layout/SelectTable.vue
  ui/tests/storybook/components/admin/Triggers.stories.jsx
  ui/tsconfig.json
Labels: area/frontend
