Repository kestra-io/kestra, pull requests merged in 2025-10, with the labels that each got.

#11518 chore(fix): Changed the iteration value of ForEachItem to 0 instead of 1
  core/src/main/java/io/kestra/core/models/executions/TaskRun.java
  core/src/main/java/io/kestra/core/models/tasks/ResolvedTask.java
  core/src/main/java/io/kestra/plugin/core/flow/ForEachItem.java
  core/src/test/java/io/kestra/plugin/core/flow/ForEachItemCaseTest.java
Labels: kind/breaking-change

#11685 feat(executions): improve performance of PurgeExecutions by batch del…
  core/src/main/java/io/kestra/core/repositories/ExecutionRepositoryInterface.java
  core/src/main/java/io/kestra/core/repositories/LogRepositoryInterface.java
  core/src/main/java/io/kestra/core/repositories/MetricRepositoryInterface.java
  core/src/main/java/io/kestra/core/services/ExecutionService.java
  core/src/main/java/io/kestra/plugin/core/execution/PurgeExecutions.java
  core/src/test/java/io/kestra/core/repositories/AbstractExecutionRepositoryTest.java
  core/src/test/java/io/kestra/core/repositories/AbstractExecutionServiceTest.java
  core/src/test/java/io/kestra/core/repositories/AbstractLogRepositoryTest.java
  core/src/test/java/io/kestra/core/repositories/AbstractMetricRepositoryTest.java
  jdbc/src/main/java/io/kestra/jdbc/repository/AbstractJdbcExecutionRepository.java
  jdbc/src/main/java/io/kestra/jdbc/repository/AbstractJdbcLogRepository.java
  jdbc/src/main/java/io/kestra/jdbc/repository/AbstractJdbcMetricRepository.java
Labels: kind/performance

#11762 docs(templates): add mention to star repo
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/pull_request_template.md
Labels: area/docs
