Repository kestra-io/kestra, pull requests merged in 2025-05, with the labels that each got.

#8620 feat(flows)!: evaluate flow trigger on PAUSED by default
  core/src/main/java/io/kestra/plugin/core/trigger/Flow.java
  core/src/test/java/io/kestra/core/repositories/AbstractFlowRepositoryTest.java
  core/src/test/java/io/kestra/core/runners/AbstractRunnerTest.java
  core/src/test/java/io/kestra/core/runners/MultipleConditionTriggerCaseTest.java
  core/src/test/resources/flows/valids/flow-trigger-paused-flow.yaml
  core/src/test/resources/flows/valids/flow-trigger-paused-listen.yaml
  webserver/src/test/java/io/kestra/webserver/controllers/api/FlowControllerTest.java
Labels: kind/breaking-change, kind/do-not-merge

#8708 fix(system): avoid catching JVM fatal error on Worker
  core/src/main/java/io/kestra/core/runners/AbstractWorkerCallable.java
  core/src/main/java/io/kestra/core/utils/Exceptions.java
Labels: area/backend, kind/customer-request, kind/backport-needed

#8800 chore(system): improve performance of IdUtils.fromParts()
  core/src/main/java/io/kestra/core/utils/IdUtils.java
Labels: kind/performance

#9102 fix(system): wait for grace period before reemitting tasks for terminated_forced workers
  core/src/main/java/io/kestra/core/server/AbstractServiceLivenessCoordinator.java
Labels: bug, area/backend, kind/backport-needed
