Repository kestra-io/kestra, pull requests merged in 2025-09, with the labels that each got.

#11086 fix(flow)*: properly handle tab closing by clicking the cross icon in the corner of the panel
  ui/src/stores/editor.ts
Labels: kind/backport-needed

#11169 chore(flows): display correct flow dependency count
  ui/src/components/flows/FlowRoot.vue
Labels: kind/backport-needed

#11238 fix(plugins): remove regex validation on version property
  core/src/main/java/io/kestra/core/models/PluginVersioning.java
  core/src/main/java/io/kestra/core/utils/Version.java
  core/src/test/java/io/kestra/core/utils/VersionTest.java
Labels: bug, area/backend, enhancement

#11374 docs(overview): new video
  README.md
Labels: area/docs
